etl:
  input: 
    # - "data/raw/emergency/"
    - /content/drive/MyDrive/data_THCIC/emergency/
    - /content/drive/MyDrive/data_THCIC/inpatient/
    - /content/drive/MyDrive/data_THCIC/outpatient/

  output: 
    # - "/content/synthetic-population_/data/bronze/"
    - "/content/synthetic-population_/data/transformed/"

database:
  hostname: 'localhost'
  port: 5432
  database: 'postgres'
  dbname: "thcic_db"
  username: "postgres"
  password: "Nazrawi123!"

# database:
#   type: sqlite
#   dbname: 'thcic_db'


ingestion:
  input:
    - "/content/synthetic-population_/data/transformed/df_base_1_emergency/"
    - "/content/synthetic-population_/data/transformed/df_grouper_emergency/"
    - "/content/synthetic-population_/data/transformed/df_base_1_inpatient/"
    - "/content/synthetic-population_/data/transformed/df_grouper_inpatient/"
    - "/content/synthetic-population_/data/transformed/df_base_1_outpatient/"
    - "/content/synthetic-population_/data/transformed/df_grouper_outpatient/"
  output: "/content/synthetic-population_/data/gold/"
  test_size: 0.2
  random_state: 42


generate:
  input: "/content/synthetic-population_/data/gold/train.csv"
  output: "/content/synthetic-population_/data/gold/generate/"

validate:
  input: 
    - "/content/synthetic-population_/data/gold/test.csv"
  output:
    - "/content/synthetic-population_/data/gold/genrated/"
    

train:
  input: 
    # - "/content/synthetic-population_/data/gold/generate/synthetic_emergency.csv"
    - "/content/synthetic-population_/data/gold/generate/synthetic_emergency.csv"

  output: 
    - "/content/synthetic-population_/model/"

evaluate:
  input:
    - "/content/synthetic-population_/data/gold/generate/synthetic_emergency.csv"
    - "/content/synthetic-population_/data/gold/test.csv"
    - "/content/synthetic-population_/data/gold/train.csv"
    - "/content/synthetic-population_/model/model.pkl"

  output:
    - "/content/synthetic-population_/assets/"





