# ==============================
# ETL / Transform
# ==============================
etl:
  input: 
    - "/content/drive/MyDrive/data_THCIC/emergency/"
    - "/content/drive/MyDrive/data_THCIC/inpatient/"
    - "/content/drive/MyDrive/data_THCIC/outpatient/"

  output: 
    - "/content/drive/MyDrive/data_THCIC/transformed/"  # ETL outputs go to Drive

# ==============================
# Database Config (Optional)
# ==============================
database:
  hostname: 'localhost'
  port: 5432
  database: 'postgres'
  dbname: "thcic_db"
  username: "postgres"
  password: "Nazrawi123!"

# ==============================
# Ingestion
# ==============================
ingestion:
  input_dir: "/content/drive/MyDrive/data_THCIC/transformed/"  # all df_base_1_* / df_grouper_* folders
  output: "/content/drive/MyDrive/data_THCIC/gold/"           # final CSV, train/test
  test_size: 0.2
  random_state: 42

# ==============================
# Data Generation
# ==============================
generate:
  input: "/content/drive/MyDrive/data_THCIC/gold/train.csv"
  output: "/content/drive/MyDrive/data_THCIC/gold/generated/"  # synthetic data on Drive

# ==============================
# Validation
# ==============================
validate:
  input: 
    - "/content/drive/MyDrive/data_THCIC/gold/test.csv"
  output:
    - "/content/drive/MyDrive/data_THCIC/gold/generated/"

# ==============================
# Model Training
# ==============================
train:
  input: 
    - "/content/drive/MyDrive/data_THCIC/gold/generated/synthetic_emergency.csv"
  output: 
    - "synthetic-population_/model/"   # Models stay in repo

# ==============================
# Model Evaluation
# ==============================
evaluate:
  input:
    - "/content/drive/MyDrive/data_THCIC/gold/generated/synthetic_emergency.csv"
    - "/content/drive/MyDrive/data_THCIC/gold/test.csv"
    - "/content/drive/MyDrive/data_THCIC/gold/train.csv"
    - "synthetic-population_/model/model.pkl"  # Model from repo
  output:
    - "synthetic-population_/assets/"          # Evaluation outputs stay in repo
